version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - URL_DATABASE=mariadb+pymysql://root:ahrarbinaslam@mariadb:3306/ssh_key_management
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data:/data

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ahrarbinaslam
      MYSQL_DATABASE: ssh_key_management
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
